[package]
name = "acs_data_extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acs = { path = "../acs" }
png = "0.17.7"